---

# Install nodejs use yum or apt
# https://github.com/nodesource/distributions

- name: check vars
  fail: msg="nodejs_version != 5 or 6 or 7"
  when: nodejs_version != 5 and nodejs_version != 6 and nodejs_version != 7

- include_tasks: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "CentOS"
#
- name: install node.js package globally.
  npm:
    name: "{{ item }}"
    global: yes
  ignore_errors: yes
  with_items:
    - "{{ install_packages }}"
  when: install_packages is defined
