---

# Install nodejs use yum or apt
# https://github.com/nodesource/distributions

- name: check required variables
  assert:
    that:
      - "{{ item }} is defined"
    fail_msg: "{{ item }} is undefined"
  with_items:
    - "{{ required_vars }}"

- name: check variables (nodejs_version)
  fail: msg="nodejs_version must be 5, 6, 7 or 8"
  when: nodejs_version != 5 and nodejs_version != 6 and nodejs_version != 7 and nodejs_version != 8

- include_tasks: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "CentOS"

- name: install node.js package globally.
  npm:
    name: "{{ item }}"
    global: yes
  ignore_errors: yes
  with_items:
    - "{{ install_packages }}"
  when: install_packages is defined

- name: create .npm
  file:
    path: "{{ npm_user_home_path }}/.npm"
    state: directory
    owner: "{{ npm_user }}"
    group: "{{ npm_user }}"
    mode: 0700
  become: yes
